version: '3.7'
services:
    sr-provider:
        build: .
        command: bash runserver.sh
        volumes:
            - ./:/usr/src/app/
        environment:
            - DEBUG=False
            # - SECRET_KEY=foo
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DB=postgres
            - SQL_USER=postgres
            - SQL_PASSWORD=postgres
            - SQL_HOST=postgres-service-provider
            - SQL_PORT=5432
        depends_on:
            - postgres-service-provider
     
    postgres-service-provider:
        image: postgres:12.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

    nginx-service-provider:
        image: nginx
        volumes:
            - ./nginx_conf:/etc/nginx/conf.d
            - ./media:/usr/src/app/media
        ports:
            - 8888:80
        depends_on:
            - sr-provider

volumes:
  postgres_data: