# Generated by Django 3.2 on 2022-11-22 10:35

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('st_name', models.CharField(max_length=250, verbose_name='اسم الشارع')),
                ('block_num', models.IntegerField(verbose_name='رقم المبنى')),
                ('floor', models.IntegerField(verbose_name='الطابق')),
                ('apartment_num', models.IntegerField(verbose_name='رقم الشقة')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='الاسم')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكترونى')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.address', verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('status', models.IntegerField(choices=[(1, 'تمت العملية بنجاح'), (2, 'تمت الموافقة على الطلب '), (3, 'تم ارسال الطلب و هو الان تحت المراجعة '), (4, 'تم رفض الطلب')], default=3, verbose_name='حالة الطلب')),
                ('cancel_order', models.BooleanField(blank=True, null=True, verbose_name='الغاء الطلب')),
                ('contact_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم التواصل')),
                ('address', models.CharField(max_length=250, verbose_name='العنوان')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب العميل',
                'verbose_name_plural': 'طلبات العملاء',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(max_length=250, verbose_name='الدولة')),
                ('postal_code', models.CharField(max_length=250, verbose_name='كود الدولة')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
            },
        ),
        migrations.CreateModel(
            name='ProviderTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('technical_name', models.CharField(max_length=200, verbose_name='اسم الفنى')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='رقم التواصل')),
            ],
            options={
                'verbose_name': 'فنى',
                'verbose_name_plural': 'الفنين',
            },
        ),
        migrations.CreateModel(
            name='ProviderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نوع مزود خدمة',
                'verbose_name_plural': 'أنواع مزودين الخدمات',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('city', models.CharField(max_length=250, verbose_name='المدينة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='المدن', to='app.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'منطقة الخدمة',
                'verbose_name_plural': 'مناطق الخدمات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(max_length=250, verbose_name='اسم الخدمة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='المحتوى')),
                ('approaved', models.BooleanField(blank=True, null=True, verbose_name='مفعلة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('field_name', models.CharField(max_length=250, verbose_name='اسم المجال')),
            ],
            options={
                'verbose_name': 'مجال خدمة',
                'verbose_name_plural': 'مجالات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(max_length=250, verbose_name='اسم المتطلب')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم المعروض للعميل')),
            ],
            options={
                'verbose_name': 'متطلب خدمة',
                'verbose_name_plural': 'متطلبات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(max_length=250, verbose_name='اسم الخدمة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='المحتوى')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subservices', to='app.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة فرعية',
                'verbose_name_plural': ' الخدمات الفرعية',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('answer', models.CharField(max_length=255, verbose_name='الاجابة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirments_requests', to='app.client', verbose_name='العميل')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.servicerequirement', verbose_name='المتطلب')),
            ],
            options={
                'verbose_name': ' اجابة متطلب خدمة',
                'verbose_name_plural': 'اجابات متطلبات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirementChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('choice', models.CharField(max_length=255, verbose_name='الاختيار المعروض للعميل')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='app.servicerequirement', verbose_name='المتطلب')),
            ],
            options={
                'verbose_name': 'اجابة مسموحة للمتطلب',
                'verbose_name_plural': ' اجابات مسموحة للمتطلبات ',
            },
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_requirements', to='app.subservice', verbose_name='خاص بالخدمة الفرعية'),
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='app.service', verbose_name='الخدمة'),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('name', models.CharField(max_length=250, verbose_name='الاسم')),
                ('commercial_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='الاسم التجارى')),
                ('owner', models.CharField(max_length=250, verbose_name='اسم المالك')),
                ('commercial_record', models.BooleanField(verbose_name='لدى سجل تجارى')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='رقم التواصل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكترونى')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='app.providertype', verbose_name='نوع مزود الخدمة')),
            ],
            options={
                'verbose_name': 'مزود خدمة',
                'verbose_name_plural': 'مزودين الخدمات',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='app.serviceprovider', verbose_name='المزود'),
        ),
        migrations.AddField(
            model_name='service',
            name='region',
            field=models.ManyToManyField(related_name='الخدمات', to='app.Region', verbose_name='المناطق'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='app.servicefield', verbose_name='مجال الخدمة'),
        ),
        migrations.CreateModel(
            name='ProviderTechnicalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='app.serviceprovider', verbose_name='مزود الخدمة التابع له')),
                ('team_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='app.servicefield', verbose_name='المجال التابع له')),
                ('team_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='app.region', verbose_name='المكان التابع له')),
                ('technicals', models.ManyToManyField(to='app.ProviderTechnical', verbose_name='الفنين')),
            ],
            options={
                'verbose_name': 'فريق من الفنين',
                'verbose_name_plural': 'فرق من الفنين',
            },
        ),
        migrations.AddField(
            model_name='providertechnical',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technicals', to='app.serviceprovider', verbose_name='مزود الخدمة التابع له'),
        ),
        migrations.AddField(
            model_name='providertechnical',
            name='technical_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technicals', to='app.servicefield', verbose_name='المجال التابع له'),
        ),
        migrations.AddField(
            model_name='providertechnical',
            name='technical_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technicals', to='app.region', verbose_name='المكان التابع له'),
        ),
        migrations.CreateModel(
            name='OrderFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('comment', models.CharField(blank=True, max_length=355, null=True, verbose_name='التعليق')),
                ('rate', models.IntegerField(blank=True, choices=[(1, 'very bad'), (2, 'Bad'), (3, 'Good'), (4, 'very good'), (5, 'Exclent')], null=True, verbose_name='التقييم')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='app.client', verbose_name='العميل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='app.clientorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': ' تقييم طلب العميل',
                'verbose_name_plural': 'تقييمات طلبات العملاء',
            },
        ),
        migrations.AddField(
            model_name='clientorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.service', verbose_name='الخدمة المطلوبة'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='team_name',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.providertechnicalteam', verbose_name='اسم فريق الفنين '),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='technical_name',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.providertechnical', verbose_name='اسم الفنى '),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='app.region', verbose_name='المنطقة'),
        ),
    ]
