# Generated by Django 3.2 on 2022-11-22 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='desired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الميعاد'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='team_name',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.providertechnicalteam', verbose_name=' فريق الفنين '),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='technical_name',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.providertechnical', verbose_name=' الفنى '),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='السعر')),
                ('expiration_date', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='app.service', verbose_name='الخدمة')),
                ('sub_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='app.subservice', verbose_name='خدمة فرعية')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
            },
        ),
    ]
