# Generated by Django 3.2 on 2022-11-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221122_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.offer', verbose_name='العرض'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.subservice', verbose_name='الخدمة الفرعية المطلوية'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.service', verbose_name='الخدمة المطلوبة'),
        ),
    ]
