# Generated by Django 3.2 on 2022-12-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(1, 'client'), (2, 'provider'), (3, 'admin')], default=1, verbose_name='نوع العميل'),
        ),
    ]
