# Generated by Django 3.2 on 2022-12-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequirementrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_requirements_requests', to='app.clientorder', verbose_name='المتطلبات الخاصة بالطلب'),
        ),
    ]
