# Generated by Django 3.2 on 2023-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_servicerequirementrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'تمت العملية بنجاح'), (2, 'تمت الموافقة على الطلب '), (3, 'تم ارسال الطلب و هو الان تحت المراجعة '), (4, 'تم رفض الطلب'), (5, 'تم الغاء الطلب بناءا على رغبة العميل ')], default=3, verbose_name='حالة الطلب'),
        ),
    ]
